spring:
  datasource:
    url: jdbc:h2:file:./data/interpoldb
    username: sa
    password: password
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    mvc:
      hiddenmethod:
        filter:
          enabled: true